### ISSUE TITLE
RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by javiersantos** [javiersantos/WhatsAppBetaUpdater#33]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at com.javiersantos.whatsappbetaupdater.util.UtilsAsync.getLatestWhatsAppVersion(UtilsAsync.java:335)
       at com.javiersantos.whatsappbetaupdater.util.UtilsAsync$NotifyWhatsAppVersion.doInBackground(UtilsAsync.java:107)
       at com.javiersantos.whatsappbetaupdater.util.UtilsAsync$NotifyWhatsAppVersion.doInBackground(UtilsAsync.java:94)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by cevem** [comment]
Did you post on StackOverflow?

**Comment by javiersantos** [comment]
Fixed in [latest update](https://github.com/javiersantos/WhatsAppBetaUpdater/releases/latest).
